export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const RESET_USER_PROFILE = 'RESET_USER_PROFILE';
export const SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN';
export const SET_CONFIG = 'SET_CONFIG';
